# Generated by Django 2.1 on 2018-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status_options',
            field=models.TextField(blank=True, default='GUIDE: Pending, Paid, Cancelled', null=True),
        ),
    ]
