# Generated by Django 2.1 on 2018-10-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status_button',
            field=models.CharField(blank=True, default='primary', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_options',
            field=models.TextField(blank=True, default='Status(button): Pending (primary), Paid(success), Cancelled(danger)', null=True),
        ),
    ]
