# Generated by Django 2.1 on 2018-09-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_booking_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
