# Generated by Django 2.1 on 2018-09-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180913_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_date',
            new_name='book_end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_time',
            new_name='book_start_date',
        ),
    ]
