# Generated by Django 2.1 on 2018-09-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180913_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
