# Generated by Django 2.1 on 2018-09-13 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180913_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_available',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=0, upload_to='img/car_images'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 8, 53, 52, 551421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 8, 53, 52, 551421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='lat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='lng',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
