# Generated by Django 2.1 on 2018-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180913_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_end_time',
            field=models.DateTimeField(default=0),
        ),
    ]
