# Generated by Django 2.1 on 2018-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180913_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=0, upload_to='car_images'),
        ),
    ]
