# Generated by Django 2.1 on 2018-09-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180913_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.Car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_available',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='is_availables', to='accounts.Car'),
        ),
    ]
