# Generated by Django 2.1 on 2018-09-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180913_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Car'),
        ),
    ]
