# Generated by Django 2.1 on 2018-09-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180913_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='image',
        ),
    ]
