# Generated by Django 2.1 on 2018-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20180913_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=0, upload_to='car_images'),
        ),
    ]
