# Generated by Django 2.1 on 2018-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180913_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='lat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='lng',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
