# Generated by Django 2.1 on 2018-09-15 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20180914_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Availablility'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
