# Generated by Django 2.1 on 2018-09-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20180915_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_end_time',
            new_name='book_end_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
