# Generated by Django 2.1 on 2018-09-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20180915_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
