# Generated by Django 2.1 on 2018-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20180917_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price per day'),
        ),
    ]
