# Generated by Django 2.1 on 2018-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20180917_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
    ]
