# Generated by Django 2.1 on 2018-09-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20180919_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
    ]
