# Generated by Django 2.1 on 2018-09-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20180919_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='car_id',
            new_name='car',
        ),
    ]
