# Generated by Django 2.1 on 2018-09-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20180919_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_available',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Availability', to='accounts.Car'),
        ),
    ]
