# Generated by Django 2.1 on 2018-09-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_booking_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Availability', to='accounts.Car'),
        ),
    ]
