# Generated by Django 2.1 on 2018-09-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20180919_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Available', to='accounts.Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, null=True, verbose_name='Availability'),
        ),
    ]
