# Generated by Django 2.1 on 2018-09-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20180919_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_available',
        ),
    ]
