# Generated by Django 2.1 on 2018-09-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_booking_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('avail_id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Is Available')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Car', verbose_name='Cars'),
        ),
        migrations.AddField(
            model_name='booking',
            name='available',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Available', verbose_name='Car Available'),
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Available', verbose_name='Is Available'),
        ),
    ]
