# Generated by Django 2.1 on 2018-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20180919_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='available',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is Available'),
        ),
    ]
