# Generated by Django 2.1 on 2018-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20180919_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='available',
        ),
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is Available'),
        ),
        migrations.DeleteModel(
            name='Available',
        ),
    ]
