# Generated by Django 2.1 on 2018-09-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20180920_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_start_date',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
    ]
