# Generated by Django 2.1 on 2018-10-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_car_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_end_time',
            field=models.TimeField(null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='book_start_time',
            field=models.TimeField(null=True, verbose_name='Start time'),
        ),
    ]
