# Generated by Django 2.1 on 2018-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_car_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='icon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Car Image Icon'),
        ),
    ]
