# Generated by Django 2.1 on 2018-10-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20181003_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='book_start_time',
            new_name='start_time',
        ),
    ]
