# Generated by Django 2.1 on 2018-10-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20181003_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='icon',
        ),
    ]
