# Generated by Django 2.1 on 2018-10-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_car_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='icon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Car Image Icon'),
        ),
    ]
