# Generated by Django 2.1 on 2018-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_car_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
