# Generated by Django 2.1 on 2018-10-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
