# Generated by Django 2.1 on 2018-10-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181012_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_options',
            field=models.TextField(blank=True, default='Status(button): Pending (primary), Paid(success), Cancelled(danger)', max_length=20, null=True),
        ),
    ]
